import { z } from "zod";
import {
  ListenOptions,
  InboundOptions,
  FwMark,
  Network,
  UDPOverTCPOptions,
  ServerOptions,
  DialerOptions,
} from "../shared";
import { listable } from "../../utils";

export const HTTPProxyOptions = z.object({
  enabled: z.boolean().optional().describe("Enable system HTTP proxy."),
  server: z.string().describe("HTTP proxy server address."),
  server_port: z.number().int().describe("HTTP proxy server port."),
  bypass_domain: listable(z.string())
    .optional()
    .describe("Hostnames that bypass the HTTP proxy."),
  match_domain: listable(z.string())
    .optional()
    .describe("Hostnames that use the HTTP proxy."),
});

export const TunPlatformOptions = z.object({
  http_proxy: HTTPProxyOptions.optional().describe(
    "System HTTP proxy settings."
  ),
});

export const TunInboundOptions = z.object({
  type: z.literal("tun"),
  tag: z.string().optional(),
  interface_name: z
    .string()
    .optional()
    .describe("Virtual device name, automatically selected if empty."),
  address: listable(z.string())
    .optional()
    .describe("IPv4 and IPv6 prefix for the tun interface."),
  mtu: z.number().int().optional().describe("The maximum transmission unit."),
  auto_route: z
    .boolean()
    .optional()
    .describe("Set the default route to the Tun."),
  iproute2_table_index: z
    .number()
    .int()
    .optional()
    .describe("Linux iproute2 table index generated by `auto_route`."),
  iproute2_rule_index: z
    .number()
    .int()
    .optional()
    .describe("Linux iproute2 rule start index generated by `auto_route`."),
  auto_redirect: z
    .boolean()
    .optional()
    .describe("Improve TUN routing and performance using nftables."),
  auto_redirect_input_mark: FwMark.optional().describe(
    "Connection input mark used by `auto_redirect`."
  ),
  auto_redirect_output_mark: FwMark.optional().describe(
    "Connection output mark used by `auto_redirect`."
  ),
  loopback_address: listable(z.string())
    .optional()
    .describe(
      "Loopback addresses make TCP connections to the specified address connect to the source address."
    ),
  strict_route: z
    .boolean()
    .optional()
    .describe("Enforce strict routing rules when `auto_route` is enabled."),
  route_address: listable(z.string())
    .optional()
    .describe(
      "Use custom routes instead of default when `auto_route` is enabled."
    ),
  route_address_set: listable(z.string())
    .optional()
    .describe(
      "Add the destination IP CIDR rules in the specified rule-sets to the firewall."
    ),
  route_exclude_address: listable(z.string())
    .optional()
    .describe("Exclude custom routes when `auto_route` is enabled."),
  route_exclude_address_set: listable(z.string())
    .optional()
    .describe(
      "Add the destination IP CIDR rules in the specified rule-sets to the firewall."
    ),
  include_interface: listable(z.string())
    .optional()
    .describe("Limit interfaces in route."),
  exclude_interface: listable(z.string())
    .optional()
    .describe("Exclude interfaces in route."),
  include_uid: listable(z.number().int())
    .optional()
    .describe("Limit users in route."),
  include_uid_range: listable(z.string())
    .optional()
    .describe("Limit users in route, but in range."),
  exclude_uid: listable(z.number().int())
    .optional()
    .describe("Exclude users in route."),
  exclude_uid_range: listable(z.string())
    .optional()
    .describe("Exclude users in route, but in range."),
  include_android_user: listable(z.number().int())
    .optional()
    .describe("Limit android users in route."),
  include_package: listable(z.string())
    .optional()
    .describe("Limit android packages in route."),
  exclude_package: listable(z.string())
    .optional()
    .describe("Exclude android packages in route."),
  stack: z
    .enum(["system", "gvisor", "mixed"])
    .optional()
    .describe("TCP/IP stack."),
  platform: TunPlatformOptions.optional().describe(
    "Platform-specific settings, provided by client applications."
  ),

  // Deprecated fields
  gso: z
    .boolean()
    .optional()
    .describe(
      "Deprecated: GSO has no advantages for transparent proxy scenarios."
    ),
  inet4_address: listable(z.string())
    .optional()
    .describe("Deprecated: merged to `address`."),
  inet6_address: listable(z.string())
    .optional()
    .describe("Deprecated: merged to `address`."),
  inet4_route_address: listable(z.string())
    .optional()
    .describe("Deprecated: merged to `route_address`."),
  inet6_route_address: listable(z.string())
    .optional()
    .describe("Deprecated: merged to `route_address`."),
  inet4_route_exclude_address: listable(z.string())
    .optional()
    .describe("Deprecated: merged to `route_exclude_address`."),
  inet6_route_exclude_address: listable(z.string())
    .optional()
    .describe("Deprecated: merged to `route_exclude_address`."),
  endpoint_independent_nat: z
    .boolean()
    .optional()
    .describe("Deprecated: This item is only available on the gvisor stack."),

  ...ListenOptions.shape,
});

export type TunInboundOptions = z.infer<typeof TunInboundOptions>;
