import { z } from "zod";
import { listableInts, listableString } from "../../utils";
import { FwMark, ListenOptions } from "../shared";

export const HTTPProxyOptions = z.object({
  enabled: z.boolean().optional().meta({
    description: "Enable system HTTP proxy.",
    description_zh: "启用系统 HTTP 代理。",
  }),
  server: z.string().meta({
    description: "HTTP proxy server address.",
    description_zh: "系统 HTTP 代理服务器地址。",
  }),
  server_port: z.number().int().meta({
    description: "HTTP proxy server port.",
    description_zh: "系统 HTTP 代理服务器端口。",
  }),
  bypass_domain: listableString.optional().meta({
    description: "Hostnames that bypass the HTTP proxy.",
    description_zh: "绕过代理的主机名列表。",
  }),
  match_domain: listableString.optional().meta({
    description: "Hostnames that use the HTTP proxy.",
    description_zh: "代理的主机名列表。",
  }),
});

export const TunPlatformOptions = z.object({
  http_proxy: HTTPProxyOptions.optional().meta({
    description: "System HTTP proxy settings.",
    description_zh: "系统 HTTP 代理设置。",
  }),
});

export const TunInboundOptions = z
  .object({
    type: z.literal("tun"),
    tag: z.string().optional(),
    interface_name: z.string().optional().meta({
      description: "Virtual device name, automatically selected if empty.",
      description_zh: "虚拟设备名称，默认自动选择。",
    }),
    address: listableString.optional().meta({
      description: "IPv4 and IPv6 prefix for the tun interface.",
      description_zh: "tun 接口的 IPv4 和 IPv6 前缀。",
    }),
    mtu: z.number().int().optional().meta({
      description: "The maximum transmission unit.",
      description_zh: "最大传输单元。",
    }),
    auto_route: z.boolean().optional().meta({
      description: "Set the default route to the Tun.",
      description_zh: "设置到 Tun 的默认路由。",
    }),
    iproute2_table_index: z.number().int().optional().meta({
      description: "Linux iproute2 table index generated by `auto_route`.",
      description_zh: "`auto_route` 生成的 iproute2 路由表索引。",
    }),
    iproute2_rule_index: z.number().int().optional().meta({
      description: "Linux iproute2 rule start index generated by `auto_route`.",
      description_zh: "`auto_route` 生成的 iproute2 规则起始索引。",
    }),
    auto_redirect: z.boolean().optional().meta({
      description: "Improve TUN routing and performance using nftables.",
      description_zh: "通过使用 nftables 改善 TUN 路由和性能。",
    }),
    auto_redirect_input_mark: FwMark.optional().meta({
      description: "Connection input mark used by `auto_redirect`.",
      description_zh: "`auto_redirect` 使用的连接输入标记。",
    }),
    auto_redirect_output_mark: FwMark.optional().meta({
      description: "Connection output mark used by `auto_redirect`.",
      description_zh: "`auto_redirect` 使用的连接输出标记。",
    }),
    strict_route: z.boolean().optional().meta({
      description: "Enforce strict routing rules when `auto_route` is enabled.",
      description_zh: "当启用 `auto_route` 时，强制执行严格的路由规则。",
    }),
    route_address: listableString.optional().meta({
      description:
        "Use custom routes instead of default when `auto_route` is enabled.",
      description_zh: "设置到 Tun 的自定义路由。",
    }),
    route_address_set: listableString.optional().meta({
      description:
        "Add the destination IP CIDR rules in the specified rule-sets to the firewall.",
      description_zh: "将指定规则集中的目标 IP CIDR 规则添加到防火墙。",
    }),
    route_exclude_address: listableString.optional().meta({
      description: "Exclude custom routes when `auto_route` is enabled.",
      description_zh: "设置到 Tun 的排除自定义路由。",
    }),
    route_exclude_address_set: listableString.optional().meta({
      description:
        "Add the destination IP CIDR rules in the specified rule-sets to the firewall.",
      description_zh: "将指定规则集中的目标 IP CIDR 规则添加到防火墙。",
    }),
    include_interface: listableString.optional().meta({
      description: "Limit interfaces in route.",
      description_zh: "限制被路由的接口。",
    }),
    exclude_interface: listableString.optional().meta({
      description: "Exclude interfaces in route.",
      description_zh: "排除路由的接口。",
    }),
    include_uid: listableInts.optional().meta({
      description: "Limit users in route.",
      description_zh: "限制被路由的用户。",
    }),
    include_uid_range: listableString.optional().meta({
      description: "Limit users in route, but in range.",
      description_zh: "限制被路由的用户范围。",
    }),
    exclude_uid: listableInts.optional().meta({
      description: "Exclude users in route.",
      description_zh: "排除路由的用户。",
    }),
    exclude_uid_range: listableString.optional().meta({
      description: "Exclude users in route, but in range.",
      description_zh: "排除路由的用户范围。",
    }),
    include_android_user: listableInts.optional().meta({
      description: "Limit android users in route.",
      description_zh: "限制被路由的 Android 用户。",
    }),
    include_package: listableString.optional().meta({
      description: "Limit android packages in route.",
      description_zh: "限制被路由的 Android 应用包名。",
    }),
    exclude_package: listableString.optional().meta({
      description: "Exclude android packages in route.",
      description_zh: "排除路由的 Android 应用包名。",
    }),
    stack: z.enum(["system", "gvisor", "mixed"]).optional().meta({
      description: "TCP/IP stack.",
      description_zh: "TCP/IP 栈。",
    }),
    platform: TunPlatformOptions.optional().meta({
      description:
        "Platform-specific settings, provided by client applications.",
      description_zh: "平台特定的设置，由客户端应用提供。",
    }),

    // Deprecated fields
    gso: z.boolean().optional().meta({
      description: "Enable generic segmentation offload.",
      description_zh: "启用通用分段卸载。",
      deprecated: true,
    }),
    inet4_address: listableString.optional().meta({
      description: "IPv4 prefix for the tun interface.",
      description_zh: "tun 接口的 IPv4 前缀。",
      deprecated: true,
    }),
    inet6_address: listableString.optional().meta({
      description: "IPv6 prefix for the tun interface.",
      description_zh: "tun 接口的 IPv6 前缀。",
      deprecated: true,
    }),
    inet4_route_address: listableString.optional().meta({
      description:
        "Use custom routes instead of default when `auto_route` is enabled.",
      description_zh: "启用 `auto_route` 时使用自定义路由而不是默认路由。",
      deprecated: true,
    }),
    inet6_route_address: listableString.optional().meta({
      description:
        "Use custom routes instead of default when `auto_route` is enabled.",
      description_zh: "启用 `auto_route` 时使用自定义路由而不是默认路由。",
      deprecated: true,
    }),
    inet4_route_exclude_address: listableString.optional().meta({
      description: "Exclude custom routes when `auto_route` is enabled.",
      description_zh: "启用 `auto_route` 时排除自定义路由。",
      deprecated: true,
    }),
    inet6_route_exclude_address: listableString.optional().meta({
      description: "Exclude custom routes when `auto_route` is enabled.",
      description_zh: "启用 `auto_route` 时排除自定义路由。",
      deprecated: true,
    }),
    endpoint_independent_nat: z.boolean().optional().meta({
      description: "Enable endpoint-independent NAT.",
      description_zh: "启用独立于端点的 NAT。",
    }),

    ...ListenOptions.shape,
  })
  .meta({
    id: "TunInboundOptions",
    title: "Tun Inbound",
    title_zh: "Tun 入站",
  });

export type TunInboundOptions = z.infer<typeof TunInboundOptions>;
